---

  - name: Install EPEL repo
    yum: name=epel-release state=present


  - name: Download and install git
    yum: name=git state=present
  
    
  - name: Remove old files foo
    file: path=/var/docker/ state=absent
    ignore_errors: true


  - name: deploy website content
    git: repo=https://github.com/rsthakur83/dgflask-app.git
         dest=/var/docker/
         force=yes


#  - name: Copying Docker file
#    copy: src=/var/docker/app/Dockerfile dest=/var/docker remote_src=yes


  - name: Build docker image
    #command: docker build -t flaskapp:"{{ lookup('env', 'BUILD_ID')}}" /var/docker/
    command: docker build -t flaskapp:ravi /var/docker/app/Dockerfile

  - name: Run the build
    #command: docker run -tid -p 9"{{ lookup('env', 'BUILD_ID')}}":5000 webapp:"{{ lookup('env', 'BUILD_ID')}}"
    command: docker run -tid -p 9023:5000 flaskapp:ravi
