---

  - name: Install EPEL repo
    yum: name=epel-release state=present


  - name: Download and install git, docker
    yum: 
     name:
      - git
      - docker
     state: present

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true
    
  - name: Remove old files foo
    file: path=/var/docker/ state=absent
    ignore_errors: true


  - name: deploy website content
    git: repo=https://github.com/rsthakur83/dgflask-app.git
         dest=/var/docker/
         force=yes




  - name: Build docker image
    command: docker build -t flaskapp:"{{ lookup('env', 'BUILD_ID')}}" .
    #chdir: /var/docker/app
    #command: docker build -t flaskapp:ravi .
    args:
      chdir: /var/docker/app

  - name: Run the build
    command: docker run -tid -p 9"{{ lookup('env', 'BUILD_ID')}}":5000 flaskapp:"{{ lookup('env', 'BUILD_ID')}}"
    #command: docker run -tid -p 9023:5000 flaskapp:ravi
